### ISSUE TITLE
[FEATURE] 디자인 적용

### ISSUE THREAD

**Issue by SangWoo9734** [wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9#10]
### 🤸 Describe the required feature

페이지/컴포넌트의 스타일은 Figma에 제시된 디자인에 따라 스타일을 적용합니다.

### 🏊 Todo

- [ ] 검색바 디자인 적용 
- [ ] 검색 자동완성 리스트 디자인 적용
- [ ] 스타일 관련 코드 디렉토리 구조 개선
