### ISSUE TITLE
[TEST] TODO 테스트 코드 추가 및 테스트 자동화

### ISSUE THREAD

**Issue by sojinjang** [wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9#14]
### 🤸 Describe the required feature
코드 작업 시 빠른 피드백을 받고 휴먼에러를 피하기 위해 테스트 코드를 추가하기

### 🏊 Todo

- [x] test 셋업
  - [x] setupTests.ts 파일에 반복되는 import 처리 
- [x] todo 테스트 코드 작성
  - [x] context와 같은 의존성은 jest를 이용해 mocking 처리
  - [x] todo item rendering 테스트
  - [x] todo list가 비어있을 때 ... rendering 테스트
- [x] 테스트 자동화
  - [x] main branch에 PR 시 테스트 코드를 통해 자동 코드 검사

### 💬 Additional information
- typescript + jest 사용을 위해 @types/jest 라이브러리 추가했습니다.
- react와의 호환성과 createRoot API 호환 이슈로 인해 react testing library를 최신 버전인 v.14로 업그레이드 했습니다.
