### ISSUE TITLE
[REFACTOR] 코드 리팩토링

### ISSUE THREAD

**Issue by ohcmadah** [wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9#22]
### 🤸 Describe the required feature

- 여러 사람이 작성하며 생긴 일관성 없는 코드 스타일 수정
- 불필요한 state와 함수 제거
- 직관적인 변수명으로 변경
위와 같은 목적으로 리팩토링을 진행하였습니다.

### 🏊 Todo

- [x] `useSuggestions`을 q와 page를 인자로 받아 useEffect dependency array에 설정하고 변경될 경우 데이터를 불러오는 방식으로 변경
- [x] axios request config의 params 사용
- [x] Context에서 useMemo 제거
- [x] `TodoContext`에 `addTodo`와 `removeTodo` 추가
- [x] 사용하지 않는 state인 `todoText` 제거
- [x] 무한 스크롤 `IntersectionObserver` 이용하도록 변경

### 💬 Additional information

- [[commit](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/commit/9217b64fa230210f255285c70f1e9fab3e2fdacc)] `useSuggestions`에 불필요하게 존재하던 `moreSuggestion` 함수를 없애기 위해, q와 page를 인자로 받아 useEffect dependency array에 설정하고 변경될 경우 데이터를 불러오는 방식으로 변경했습니다.
- [[commit](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/pull/24/commits/df9f0f804b9ea599ec65a261f17d5871c958195e)] `?q=${q}&page=${page}&limit=${LIMIT}`처럼 직접 URL parameter 생성하는 부분을 axios request config의 params를 넘겨 대체했습니다.
- [[commit](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/pull/24/commits/85801f2900290285952cfb952896479db7c24662)] Context에서 Provider에 value를 넘길 때 사용하던 useMemo의 필요성에 의문을 가져 제거하였습니다. [react/jsx-no-constructed-context-values](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-constructed-context-values.md) 룰은 off 처리 하였습니다. 
- [[commit](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/pull/24/commits/cecafd2ad4492f187037d1358422e0b5837fc648)] `TodoContext`에서 `setTodos`를 바로 넘기는 문제와 로직이 컴포넌트에 있는 것을 수정하기 위해 `addTodo`, `removeTodo` 추가했습니다. 
- [[commit](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/pull/24/commits/c2356f17012813dc4ea77e0e33db0504a39be00b)] 검색 바에서 input value는 `SearchContext`에서 관리하고, `TodoContext`에서는 TODO list 관련 상태만 관리하도록 변경하였습니다. 따라서 사용하지 않는 state인 `todoText` 제거하였습니다. 
- [[PR](https://github.com/wanted-pre-onboarding-team-9/pre-onboarding-10th-4-9/pull/33)] `onScroll`의 경우 스크롤을 할 때마다 이벤트가 발생하여 성능상 이슈가 있을 수 있기 때문에 `IntersectionObserver`로 변경했습니다. 자세한 내용은 PR 코멘트에서 확인 가능합니다.
